/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author nathanials
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTbPaneRepresentante = new javax.swing.JTabbedPane();
        PanelCliente = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblGeneroCliente = new javax.swing.JLabel();
        lblNascCliente = new javax.swing.JLabel();
        lblEmailCliente = new javax.swing.JLabel();
        lblEnderecoCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtEmailCliente = new javax.swing.JTextField();
        txtEnderecoCliente = new javax.swing.JTextField();
        radbutFemininoCliente = new javax.swing.JRadioButton();
        radbutMasculinoCliente = new javax.swing.JRadioButton();
        fmtdTxtNascCliente = new javax.swing.JFormattedTextField();
        btnCadastrarCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnListarCliente = new javax.swing.JButton();
        PanelEndereco = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        lblBairroEndereco = new javax.swing.JLabel();
        lblCidadeEndereco = new javax.swing.JLabel();
        lblEstadoEndereco = new javax.swing.JLabel();
        lblPaisEndereco = new javax.swing.JLabel();
        lblComplEndereco = new javax.swing.JLabel();
        txtComplEndereco = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairroEndereco = new javax.swing.JTextField();
        txtCidadeEndereco = new javax.swing.JTextField();
        txtPaisEndereco = new javax.swing.JTextField();
        ComboBoxEstadoEndereco = new javax.swing.JComboBox();
        btnCadastrarEndereco = new javax.swing.JButton();
        btnAlterarEndereco = new javax.swing.JButton();
        btnExcluirEndereco = new javax.swing.JButton();
        btnListarEndereco = new javax.swing.JButton();
        PanelProdutos = new javax.swing.JPanel();
        lblNomeProduto = new javax.swing.JLabel();
        lblDescricaoProduto = new javax.swing.JLabel();
        lblValorCustoProduto = new javax.swing.JLabel();
        lblValorVendaProduto = new javax.swing.JLabel();
        txtValorVenda = new javax.swing.JTextField();
        txtValorCustoProduto = new javax.swing.JTextField();
        txtDescricaoProduto = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        btnCadastrarProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnListarProduto = new javax.swing.JButton();
        PanelEstoque = new javax.swing.JPanel();
        lblNomeEstoque = new javax.swing.JLabel();
        lblIDProdutoEstoque = new javax.swing.JLabel();
        lblQtdeEstoque = new javax.swing.JLabel();
        txtQtdeEstoque = new javax.swing.JTextField();
        txtIDProdutoEstoque = new javax.swing.JTextField();
        txtNomeEstoque = new javax.swing.JTextField();
        btnVisualizarEstoque = new javax.swing.JButton();
        PanelVendas = new javax.swing.JPanel();
        lblNomeVendas = new javax.swing.JLabel();
        lblProdutoVenda = new javax.swing.JLabel();
        lblQtdeVenda = new javax.swing.JLabel();
        lblDescontoVenda = new javax.swing.JLabel();
        lblValorTotalVenda = new javax.swing.JLabel();
        txtValorTotalVenda = new javax.swing.JTextField();
        lblValorFinalVenda = new javax.swing.JLabel();
        txtValorFinalVenda = new javax.swing.JTextField();
        btnConcluirVenda = new javax.swing.JButton();
        txtNomeVenda = new javax.swing.JTextField();
        txtProdutoVenda = new javax.swing.JTextField();
        txtQtdeVenda = new javax.swing.JTextField();
        txtDescontoVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblNomeCliente.setText("Nome");

        lblGeneroCliente.setText("Gênero");

        lblNascCliente.setText("Nascimento");

        lblEmailCliente.setText("E-mail");

        lblEnderecoCliente.setText("Endereço");

        radbutFemininoCliente.setText("Feminino");

        radbutMasculinoCliente.setText("Masculino");

        fmtdTxtNascCliente.setText("  /  /  ");

        btnCadastrarCliente.setText("Cadastrar");

        btnAlterarCliente.setText("Alterar");

        btnExcluirCliente.setText("Excluir");

        btnListarCliente.setText("Listar");
        btnListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarCliente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNascCliente)
                            .addComponent(lblGeneroCliente)
                            .addComponent(lblNomeCliente)
                            .addComponent(lblEmailCliente)
                            .addComponent(lblEnderecoCliente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(radbutFemininoCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(radbutMasculinoCliente))
                                .addComponent(txtNomeCliente)
                                .addComponent(txtEmailCliente)
                                .addComponent(txtEnderecoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                            .addComponent(fmtdTxtNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeneroCliente)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radbutFemininoCliente)
                        .addComponent(radbutMasculinoCliente)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNascCliente)
                            .addComponent(fmtdTxtNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailCliente))
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecoCliente)
                    .addComponent(txtEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarCliente)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnListarCliente))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        PanelCliente.addTab("Cliente", jPanel2);

        lblEndereco.setText("Endereço");

        lblBairroEndereco.setText("Bairro");

        lblCidadeEndereco.setText("Cidade");

        lblEstadoEndereco.setText("Estado");

        lblPaisEndereco.setText("País");

        lblComplEndereco.setText("Complemento");

        ComboBoxEstadoEndereco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        btnCadastrarEndereco.setText("Cadastrar");

        btnAlterarEndereco.setText("Alterar");

        btnExcluirEndereco.setText("Excluir");

        btnListarEndereco.setText("Listar");

        javax.swing.GroupLayout PanelEnderecoLayout = new javax.swing.GroupLayout(PanelEndereco);
        PanelEndereco.setLayout(PanelEnderecoLayout);
        PanelEnderecoLayout.setHorizontalGroup(
            PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEnderecoLayout.createSequentialGroup()
                        .addComponent(btnCadastrarEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarEndereco))
                    .addGroup(PanelEnderecoLayout.createSequentialGroup()
                        .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComplEndereco)
                            .addComponent(lblEndereco)
                            .addComponent(lblBairroEndereco)
                            .addComponent(lblCidadeEndereco)
                            .addComponent(lblPaisEndereco)
                            .addComponent(lblEstadoEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxEstadoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtComplEndereco)
                                .addComponent(txtEndereco)
                                .addComponent(txtBairroEndereco)
                                .addComponent(txtCidadeEndereco)
                                .addComponent(txtPaisEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        PanelEnderecoLayout.setVerticalGroup(
            PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnderecoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblComplEndereco)
                    .addComponent(txtComplEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairroEndereco)
                    .addComponent(txtBairroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeEndereco)
                    .addComponent(txtCidadeEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoEndereco)
                    .addComponent(ComboBoxEstadoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaisEndereco)
                    .addComponent(txtPaisEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarEndereco)
                    .addComponent(btnAlterarEndereco)
                    .addComponent(btnExcluirEndereco)
                    .addComponent(btnListarEndereco))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        PanelCliente.addTab("Endereço", PanelEndereco);

        lblNomeProduto.setText("Nome");

        lblDescricaoProduto.setText("Descrição");

        lblValorCustoProduto.setText("Valor de Custo");

        lblValorVendaProduto.setText("Valor de Venda");

        btnCadastrarProduto.setText("Cadastrar");

        btnAlterarProduto.setText("Alterar");

        btnExcluirProduto.setText("Excluir");

        btnListarProduto.setText("Listar");

        javax.swing.GroupLayout PanelProdutosLayout = new javax.swing.GroupLayout(PanelProdutos);
        PanelProdutos.setLayout(PanelProdutosLayout);
        PanelProdutosLayout.setHorizontalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorCustoProduto)
                                    .addComponent(lblDescricaoProduto))
                                .addGap(18, 18, 18)
                                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                                        .addComponent(txtValorCustoProduto)
                                        .addGap(79, 79, 79))))
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addComponent(lblValorVendaProduto)
                                .addGap(18, 18, 18)
                                .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(397, Short.MAX_VALUE))
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addComponent(btnCadastrarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAlterarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarProduto))
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblNomeProduto)
                                .addGap(61, 61, 61)
                                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelProdutosLayout.setVerticalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoProduto)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorCustoProduto)
                    .addComponent(txtValorCustoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorVendaProduto)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarProduto)
                    .addComponent(btnAlterarProduto)
                    .addComponent(btnExcluirProduto)
                    .addComponent(btnListarProduto))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        PanelCliente.addTab("Produtos", PanelProdutos);

        lblNomeEstoque.setText("Nome");

        lblIDProdutoEstoque.setText("ID Produto");

        lblQtdeEstoque.setText("Quantidade");

        btnVisualizarEstoque.setText("Visualizar");

        javax.swing.GroupLayout PanelEstoqueLayout = new javax.swing.GroupLayout(PanelEstoque);
        PanelEstoque.setLayout(PanelEstoqueLayout);
        PanelEstoqueLayout.setHorizontalGroup(
            PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstoqueLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstoqueLayout.createSequentialGroup()
                        .addComponent(lblQtdeEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(txtQtdeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVisualizarEstoque)
                        .addGroup(PanelEstoqueLayout.createSequentialGroup()
                            .addGroup(PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblIDProdutoEstoque)
                                .addComponent(lblNomeEstoque))
                            .addGap(18, 18, 18)
                            .addGroup(PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNomeEstoque)
                                .addComponent(txtIDProdutoEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))))
                .addContainerGap(455, Short.MAX_VALUE))
        );
        PanelEstoqueLayout.setVerticalGroup(
            PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstoqueLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEstoque)
                    .addComponent(txtNomeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDProdutoEstoque)
                    .addComponent(txtIDProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeEstoque)
                    .addComponent(txtQtdeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnVisualizarEstoque)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        PanelCliente.addTab("Estoque", PanelEstoque);

        lblNomeVendas.setText("Nome Cliente");

        lblProdutoVenda.setText("Produto");

        lblQtdeVenda.setText("Quantidade");

        lblDescontoVenda.setText("Desconto");

        lblValorTotalVenda.setText("Valor de Venda");

        lblValorFinalVenda.setText("Valor Total");

        btnConcluirVenda.setText("Concluir");

        javax.swing.GroupLayout PanelVendasLayout = new javax.swing.GroupLayout(PanelVendas);
        PanelVendas.setLayout(PanelVendasLayout);
        PanelVendasLayout.setHorizontalGroup(
            PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVendasLayout.createSequentialGroup()
                        .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeVendas)
                            .addComponent(lblProdutoVenda, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeVenda)
                            .addComponent(txtProdutoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)))
                    .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConcluirVenda)
                        .addGroup(PanelVendasLayout.createSequentialGroup()
                            .addComponent(lblValorTotalVenda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(lblValorFinalVenda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtValorFinalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelVendasLayout.createSequentialGroup()
                            .addComponent(lblDescontoVenda)
                            .addGap(18, 18, 18)
                            .addComponent(txtDescontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelVendasLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblQtdeVenda)
                            .addGap(18, 18, 18)
                            .addComponent(txtQtdeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        PanelVendasLayout.setVerticalGroup(
            PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVendasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeVendas)
                    .addComponent(txtNomeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdutoVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeVenda)
                    .addComponent(txtQtdeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescontoVenda))
                .addGap(13, 13, 13)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotalVenda)
                    .addComponent(txtValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorFinalVenda)
                    .addComponent(txtValorFinalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConcluirVenda)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        PanelCliente.addTab("Vendas", PanelVendas);

        jTbPaneRepresentante.addTab("Representante", PanelCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTbPaneRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTbPaneRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxEstadoEndereco;
    private javax.swing.JTabbedPane PanelCliente;
    private javax.swing.JPanel PanelEndereco;
    private javax.swing.JPanel PanelEstoque;
    private javax.swing.JPanel PanelProdutos;
    private javax.swing.JPanel PanelVendas;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnAlterarEndereco;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarEndereco;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnConcluirVenda;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnExcluirEndereco;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnListarCliente;
    private javax.swing.JButton btnListarEndereco;
    private javax.swing.JButton btnListarProduto;
    private javax.swing.JButton btnVisualizarEstoque;
    private javax.swing.JFormattedTextField fmtdTxtNascCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTbPaneRepresentante;
    private javax.swing.JLabel lblBairroEndereco;
    private javax.swing.JLabel lblCidadeEndereco;
    private javax.swing.JLabel lblComplEndereco;
    private javax.swing.JLabel lblDescontoVenda;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEnderecoCliente;
    private javax.swing.JLabel lblEstadoEndereco;
    private javax.swing.JLabel lblGeneroCliente;
    private javax.swing.JLabel lblIDProdutoEstoque;
    private javax.swing.JLabel lblNascCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeEstoque;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblNomeVendas;
    private javax.swing.JLabel lblPaisEndereco;
    private javax.swing.JLabel lblProdutoVenda;
    private javax.swing.JLabel lblQtdeEstoque;
    private javax.swing.JLabel lblQtdeVenda;
    private javax.swing.JLabel lblValorCustoProduto;
    private javax.swing.JLabel lblValorFinalVenda;
    private javax.swing.JLabel lblValorTotalVenda;
    private javax.swing.JLabel lblValorVendaProduto;
    private javax.swing.JRadioButton radbutFemininoCliente;
    private javax.swing.JRadioButton radbutMasculinoCliente;
    private javax.swing.JTextField txtBairroEndereco;
    private javax.swing.JTextField txtCidadeEndereco;
    private javax.swing.JTextField txtComplEndereco;
    private javax.swing.JTextField txtDescontoVenda;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtIDProdutoEstoque;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeEstoque;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtNomeVenda;
    private javax.swing.JTextField txtPaisEndereco;
    private javax.swing.JTextField txtProdutoVenda;
    private javax.swing.JTextField txtQtdeEstoque;
    private javax.swing.JTextField txtQtdeVenda;
    private javax.swing.JTextField txtValorCustoProduto;
    private javax.swing.JTextField txtValorFinalVenda;
    private javax.swing.JTextField txtValorTotalVenda;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
